### ISSUE TITLE
Get information by game id?

### ISSUE THREAD

**Issue by Symbai** [swiftyspiffy/EpicGamesStoreNET#2]
Would it be possible to get information by providing an EPIC game id instead of game name? For example "Pepper" for Shenmue 3 or "heather" for RDR2 ?

**Comment by swiftyspiffy** [comment]
I'm not familiar with a way of doing that with their API. If you know of a way, let me know and I can look into adding it.

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this. Feel free to reopen if you know of a way to do the above.
